package com.harvard.crimson.domain;

import static org.assertj.core.api.Assertions.assertThat;

import com.harvard.crimson.web.rest.TestUtil;
import org.junit.jupiter.api.Test;

class MoodTest {

    @Test
    void verifyMoodInit() throws Exception {
        Mood mood1 = new Mood();
        mood1.setId(1L);
        mood1.setName("mood1");
        assertThat(mood1).isNotEqualTo(null);
    }

    @Test
    void verifyMoodInitWithMeditation() throws Exception {
        Mood mood1 = new Mood();
        mood1.setId(1L);
        mood1.setName("mood1");
        Meditation meditation = new Meditation();
        mood1.setMeditation(meditation);
        assertThat(mood1).isNotEqualTo(null);
    }

    @Test
    void equalsVerifier() throws Exception {
        TestUtil.equalsVerifier(Mood.class);
        Mood mood1 = new Mood();
        mood1.setId(1L);
        Mood mood2 = new Mood();
        mood2.setId(mood1.getId());
        assertThat(mood1).isEqualTo(mood2);
    }

    @Test
    void equalsVerifierMoodId() throws Exception {
        TestUtil.equalsVerifier(Mood.class);
        Mood mood1 = new Mood();
        mood1.setId(1L);
        Mood mood2 = new Mood();
        mood2.setId(mood1.getId());
        mood2.setId(2L);
        assertThat(mood1).isNotEqualTo(mood2);
    }

    @Test
    void equalsVerifierMoodNotEqual() throws Exception {
        TestUtil.equalsVerifier(Mood.class);
        Mood mood1 = new Mood();
        mood1.setId(1L);
        Mood mood2 = new Mood();
        mood2.setId(mood1.getId());
        mood2.setId(2L);
        mood1.setId(null);
        assertThat(mood1).isNotEqualTo(mood2);
    }

    @Test
    void verifyMoodIdIsAutoGenerated() throws Exception {
        TestUtil.equalsVerifier(Mood.class);
        Mood mood1 = new Mood();
        mood1.setId(1L);
        assertThat(mood1.getId()).isNotEqualTo(null);
    }

    @Test
    void verifyMoodNameSetter() throws Exception {
        TestUtil.equalsVerifier(Mood.class);
        Mood mood1 = new Mood();
        mood1.setName("name1");
        assertThat(mood1.getName()).isNotEqualTo(null);
    }
}
